POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "DOE",
  "gender": "m",
  "roles": ["student"]
}

### delete a user | delete Jane DOE
DELETE http://localhost:8000/api/v1/users/522e2967-75e4-48e9-a922-6805ca248e66
accept: application/json

### get users
GET http://localhost:8000/api/v1/users/
